CREATE DATABASE IF NOT EXISTS user;
CREATE DATABASE IF NOT EXISTS product;
CREATE DATABASE IF NOT EXISTS auth;
CREATE DATABASE IF NOT EXISTS cart;
CREATE DATABASE IF NOT EXISTS payment;
CREATE DATABASE IF NOT EXISTS order;