version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_ROOT_PASSWORD=53516632
      - MYSQL_PORT=3307
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
